apiVersion: apps/v1
kind: Deployment

metadata:
  name: atharva-deployment
  namespace: atharva-ns
  labels:
    first: app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
      - name: atharva-container
        image: atharva7823/fitnesstracker:v1

        ports:
        - containerPort: 5000

        volumeMounts:
        - name: app-storage
          mountPath: /app/data

      volumes:
      - name: app-storage
        emptyDir: {}